apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular
    spec:
      containers:
        - image: mdnurakmal/project1-angular:latest
          name: project1-angular
          env:
          - name: AUTHSERVER_URL
            value: http://35.223.210.36:8080/ws-chat
          ports:
          - containerPort: 80
            name: nginx
          - containerPort: 8080
            name: websocket
          resources: {}

status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: websocket
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: angular-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: "mdnurakmal.com"
    http:
      paths:
      - pathType: Exact
        path: "/"
        backend:
          service:
            name: angular-service
            port:
              number: 80
  - host: "mdnurakmal.com"
    http:
      paths:
      - pathType: Exact
        path: "/ws-chat"
        backend:
          service:
            name: angular-service
            port:
              number: 8080

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - mdnurakmal.com
            
