apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular
    spec:
      containers:
        - image: mdnurakmal/project1-angular:latest
          name: project1-angular
          ports:
          - containerPort: 80
          envFrom:
            - configMapRef:
                name: angular-config
          resources: {}

status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: angular-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: angular-service
      port:
        number: 80

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - mdnurakmal.com
            