apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - image: mdnurakmal/project1-angular:latest
          name: project1-angular
          env:
          - name: AUTHSERVER_URL
            value: http://demo.default.svc.cluster.local:8080/ws-chat
          ports:
          - containerPort: 80
            name: nginx
---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS"}'
spec:
  selector:
    app: angular
  type: NodePort
  ports:
    - name: my-https-port
      port: 80
      targetPort: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: angular-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: angular-service
      port:
        number: 80


---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - mdnurakmal.com
            
